#!/bin/bash

#export CONFIG_NETFILTER_XT_TARGET_TPROXY=m
module_path=$(realpath linux-4.4.59/net/netfilter)

case ${MakeClean} in
	[Yy][Ee][Ss])
		make clean
		;;
esac

make ${MAKE_FLAGS} CROSS_COMPILE=$CROSS_COMPILE ARCH=$ARCH  CONFIG_NETFILTER_XT_TARGET_TPROXY=m -C $KSRC M=${module_path} modules 
